const state={customers:[],recipes:[],selectedCustomer:null,savedTab:"recipes",saved:{recipes:[],customers:[],employees:[],rooms:[],other:[]},pendingImage:null};
const $=s=>document.querySelector(s);
const esc=v=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const storeKey="schedule1-helper-saved-v2";
const mapCategories=[{"name":"ATM","count":16},{"name":"Recycler","count":13},{"name":"Telephone Booth","count":19},{"name":"Vending Machine","count":12},{"name":"Dead Drop","count":25},{"name":"Area / Location","count":40},{"name":"Stash","count":3},{"name":"RV","count":1},{"name":"Purchasable Area","count":5},{"name":"Main Mission","count":16},{"name":"Post Office","count":1},{"name":"Laundromat","count":1},{"name":"Car Wash","count":1},{"name":"Taco Ticklers","count":1}];
function showTab(name){document.querySelectorAll(".tab").forEach(b=>b.classList.toggle("active",b.dataset.tab===name));document.querySelectorAll(".view").forEach(v=>v.classList.toggle("active",v.id==="view-"+name));window.scrollTo({top:0,behavior:"smooth"});}
document.querySelectorAll(".tab").forEach(b=>b.addEventListener("click",()=>showTab(b.dataset.tab)));
document.querySelectorAll("[data-tab-jump]").forEach(b=>b.addEventListener("click",()=>showTab(b.dataset.tabJump)));
function loadSaved(){try{state.saved={recipes:[],customers:[],employees:[],rooms:[],other:[],...JSON.parse(localStorage.getItem(storeKey)||"{}")};}catch{state.saved={recipes:[],customers:[],employees:[],rooms:[],other:[]};}}
function persistSaved(){localStorage.setItem(storeKey,JSON.stringify(state.saved));}
function saveRecord(type,data){if(!state.saved[type])state.saved[type]=[];if(!state.saved[type].some(x=>x.key===data.key)){state.saved[type].unshift(data);persistSaved();renderSaved();}}
function renderCategories(){$("#mapCategoryList").innerHTML=mapCategories.map(x=>"<div class='category-row'><span>"+esc(x.name)+"</span><b>"+x.count+"</b></div>").join("");}
async function loadData(){const [c,r]=await Promise.all([fetch("./data/customers.json",{cache:"no-store"}).then(x=>x.json()),fetch("./data/recipes.json",{cache:"no-store"}).then(x=>x.json())]);state.customers=Array.isArray(c.customers)?c.customers:[];state.recipes=Array.isArray(r.recipes)?r.recipes:[];$("#customerCountBadge").textContent=state.customers.length;const d=[...new Set(state.customers.map(x=>x.district))].sort();$("#districtFilter").insertAdjacentHTML("beforeend",d.map(x=>"<option>"+esc(x)+"</option>").join(""));renderCategories();renderCustomers();renderRecipes();}
function cMatch(c,q,d,t){if(d&&c.district!==d)return false;if(t&&c.tier!==t)return false;if(!q)return true;return[c.name,c.district,c.tier,...c.preferred_effects].join(" ").toLowerCase().includes(q);}
function renderCustomers(){const q=$("#customerSearch").value.trim().toLowerCase(),d=$("#districtFilter").value,t=$("#tierFilter").value,list=state.customers.filter(c=>cMatch(c,q,d,t));$("#customerSummary").textContent=list.length+" z "+state.customers.length+" zákazníků zobrazených";$("#customerList").innerHTML=list.map(c=>{const sel=c.id===state.selectedCustomer?" selected":"",eff=c.preferred_effects.length?c.preferred_effects.map(e=>"<span class='effect'>"+esc(e)+"</span>").join(""):"<span class='meta'>Bez preferovaného efektu</span>";return "<article class='customer-card"+sel+"' data-id='"+c.id+"'><div class='customer-main'><div><div class='customer-name'>"+esc(c.name)+"</div><div class='meta'>"+esc(c.district)+" · "+esc(c.tier)+" · $"+c.budget+" / deal · "+esc(c.orders_per_week)+" / týden</div></div><button class='mini-save' type='button' data-save-customer='"+c.id+"'>Uložit</button></div><div class='effects'>"+eff+"</div></article>";}).join("")||"<div class='empty'>Žádný zákazník neodpovídá filtru.</div>";document.querySelectorAll(".customer-card").forEach(el=>el.addEventListener("click",e=>{if(e.target.closest("button"))return;state.selectedCustomer=Number(el.dataset.id);renderCustomers();}));document.querySelectorAll("[data-save-customer]").forEach(b=>b.addEventListener("click",e=>{e.stopPropagation();const c=state.customers.find(x=>x.id===Number(b.dataset.saveCustomer));if(c)saveRecord("customers",{key:"customer:"+c.id,name:c.name,note:c.district+" · "+c.tier+" · $"+c.budget});}));renderCustomerDetail();}
function renderCustomerDetail(){const c=state.customers.find(x=>x.id===state.selectedCustomer);if(!c){$("#customerDetail").innerHTML="<div class='empty'>Vyber zákazníka.</div>";return;}const eff=c.preferred_effects.length?c.preferred_effects.map(e=>"<span class='effect'>"+esc(e)+"</span>").join(""):"<span class='meta'>Žádné preference</span>";$("#customerDetail").innerHTML="<div class='label'>Customer profile</div><h3>"+esc(c.name)+"</h3><div class='meta'>"+esc(c.district)+" · "+esc(c.tier)+"</div><div class='detail-row'><span>Budget / deal</span><b>$"+c.budget+"</b></div><div class='detail-row'><span>Orders / week</span><b>"+esc(c.orders_per_week)+"</b></div><div class='detail-row'><span>Mapa</span><b>Souřadnice čekají na ověření</b></div><div style='margin-top:12px'><div class='meta'>Preferred effects</div><div class='effects'>"+eff+"</div></div><button class='btn primary full' id='saveSelectedCustomer'>Uložit zákazníka</button>";$("#saveSelectedCustomer").onclick=()=>saveRecord("customers",{key:"customer:"+c.id,name:c.name,note:c.district+" · "+c.tier+" · $"+c.budget});}
function matchCustomers(r){const e=new Set(r.effects.map(x=>x.toLowerCase()));return state.customers.map(c=>({...c,matchCount:c.preferred_effects.filter(x=>e.has(x.toLowerCase())).length})).filter(c=>c.matchCount>0).sort((a,b)=>b.matchCount-a.matchCount||b.budget-a.budget);}
function renderRecipes(){const q=$("#recipeSearch").value.trim().toLowerCase(),d=$("#drugFilter").value,list=state.recipes.filter(r=>(!d||r.drug===d)&&(!q||[r.name,r.drug,...r.ingredients,...r.effects].join(" ").toLowerCase().includes(q)));$("#recipeList").innerHTML=list.map((r,i)=>{const ms=matchCustomers(r),top=ms.slice(0,6).map(c=>"<button class='match-customer' type='button' data-match-customer='"+c.id+"'><span>"+esc(c.name)+" · "+esc(c.district)+"</span><b>"+c.matchCount+"/"+r.effects.length+"</b></button>").join("");return "<article class='recipe-card'><div class='recipe-head'><div><div class='label'>"+esc(r.drug)+"</div><div class='recipe-name'>"+esc(r.name)+"</div></div><div class='numbers'><div class='metric'>Náklad<b>$"+r.cost+"</b></div><div class='metric'>Prodej<b>$"+r.sell+"</b></div><div class='metric profit'>Profit<b>$"+r.profit+"</b></div></div></div><div class='ingredients'><b>Ingredience v pořadí:</b> "+r.ingredients.map(esc).join(" → ")+"</div><div class='effects'>"+r.effects.map(x=>"<span class='effect'>"+esc(x)+"</span>").join("")+"</div><div class='recipe-actions'><button class='btn primary' type='button' data-save-recipe='"+i+"'>Uložit recept</button><span class='match-count'>Effect match: "+ms.length+" zákazníků</span></div><div class='matches'><div class='matches-title'>Nejlepší effect matches</div>"+(top||"<span class='meta'>Bez shody efektů.</span>")+"</div><div class='source'>"+esc(r.source)+(r.customers!=null?" · zdroj uvádí "+r.customers+" vhodných zákazníků":"")+"</div></article>";}).join("")||"<div class='empty'>Žádný recept neodpovídá hledání.</div>";document.querySelectorAll("[data-save-recipe]").forEach(b=>b.addEventListener("click",()=>{const r=list[Number(b.dataset.saveRecipe)];if(r)saveRecord("recipes",{key:"recipe:"+r.id,name:r.name,note:r.drug+" · $"+r.profit+" profit"});}));document.querySelectorAll("[data-match-customer]").forEach(b=>b.addEventListener("click",()=>{state.selectedCustomer=Number(b.dataset.matchCustomer);showTab("customers");renderCustomers();}));}
function setSavedTab(type){state.savedTab=type;document.querySelectorAll(".saved-tab").forEach(b=>b.classList.toggle("active",b.dataset.saved===type));$("#editorTitle").textContent=type==="recipes"?"Recipe":type==="customers"?"Customer":type==="employees"?"Employee":type==="rooms"?"Room":"Other";$("#imageButton").hidden=type!=="rooms";$("#savedImage").hidden=type!=="rooms";$("#savedForm").reset();state.pendingImage=null;$("#imagePreview").hidden=true;renderSaved();}
function renderSaved(){const type=state.savedTab,items=state.saved[type]||[];$("#savedList").innerHTML=items.map((x,i)=>"<article class='saved-card'>"+(x.image?"<img class='saved-thumb' src='"+x.image+"' alt=''>":"")+"<div class='saved-card-body'><div class='saved-name'>"+esc(x.name)+"</div><div class='meta'>"+esc(x.note||"")+"</div><div class='saved-actions'>"+(type==="rooms"?"<button class='btn ghost' type='button' data-show-room='"+i+"'>Zobrazit na mapě</button>":"")+"<button class='btn ghost danger' type='button' data-delete-saved='"+i+"'>Smazat</button></div></div></article>").join("")||"<div class='empty'>Zatím nic uloženého.</div>";document.querySelectorAll("[data-delete-saved]").forEach(b=>b.addEventListener("click",()=>{state.saved[type].splice(Number(b.dataset.deleteSaved),1);persistSaved();renderSaved();}));document.querySelectorAll("[data-show-room]").forEach(b=>b.addEventListener("click",()=>{const room=state.saved.rooms[Number(b.dataset.showRoom)];sessionStorage.setItem("s1-room-highlight",room?.name||"");showTab("map");renderRoomHighlight();}));}
function renderRoomHighlight(){const name=sessionStorage.getItem("s1-room-highlight");let el=$("#roomHighlight");if(!el){el=document.createElement("div");el.id="roomHighlight";el.className="room-highlight";$("#view-map").prepend(el);}if(name){el.innerHTML="<b>Room highlight</b><span>"+esc(name)+"</span><button class='btn ghost' id='clearRoomHighlight'>Zavřít</button>";el.hidden=false;$("#clearRoomHighlight").onclick=()=>{sessionStorage.removeItem("s1-room-highlight");el.hidden=true;};}else el.hidden=true;}
$("#savedImage").addEventListener("change",e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>2000000){alert("Obrázek je příliš velký. Maximum 2 MB.");e.target.value="";return;}const rd=new FileReader();rd.onload=()=>{state.pendingImage=rd.result;$("#imagePreview").innerHTML="<img src='"+state.pendingImage+"' alt='Náhled'>";$("#imagePreview").hidden=false;};rd.readAsDataURL(file);});
$("#imageButton").addEventListener("click",()=>$("#savedImage").click());
$("#savedForm").addEventListener("submit",e=>{e.preventDefault();const type=state.savedTab,name=$("#savedName").value.trim(),note=$("#savedNote").value.trim();saveRecord(type,{key:type+":"+Date.now(),name,note,image:type==="rooms"?state.pendingImage||null:null});$("#savedName").value="";$("#savedNote").value="";state.pendingImage=null;$("#imagePreview").hidden=true;});
document.querySelectorAll(".saved-tab").forEach(b=>b.addEventListener("click",()=>setSavedTab(b.dataset.saved)));
$("#customerSearch").addEventListener("input",renderCustomers);$("#districtFilter").addEventListener("change",renderCustomers);$("#tierFilter").addEventListener("change",renderCustomers);$("#recipeSearch").addEventListener("input",renderRecipes);$("#drugFilter").addEventListener("change",renderRecipes);
let scale=1,ox=0,oy=0,drag=false,sx=0,sy=0;const vp=$("#mapViewport"),img=$("#mapImage");function applyMap(){img.style.transform="translate("+ox+"px,"+oy+"px) scale("+scale+")";}$("#zoomIn").addEventListener("click",()=>{scale=Math.min(3.2,scale+.18);applyMap();});$("#zoomOut").addEventListener("click",()=>{scale=Math.max(.72,scale-.18);applyMap();});$("#resetMap").addEventListener("click",()=>{scale=1;ox=0;oy=0;applyMap();});vp.addEventListener("wheel",e=>{e.preventDefault();scale=Math.max(.72,Math.min(3.2,scale+(e.deltaY<0?.15:-.15)));applyMap();},{passive:false});vp.addEventListener("pointerdown",e=>{drag=true;sx=e.clientX-ox;sy=e.clientY-oy;vp.setPointerCapture(e.pointerId);});vp.addEventListener("pointermove",e=>{if(!drag)return;ox=e.clientX-sx;oy=e.clientY-sy;applyMap();});vp.addEventListener("pointerup",()=>drag=false);vp.addEventListener("pointercancel",()=>drag=false);
loadSaved();setSavedTab("recipes");renderRoomHighlight();loadData().catch(err=>{console.error(err);$("#customerSummary").textContent="Data se nepodařilo načíst";});
