const STORE="schedule1-helper-saved-v2",FOLDERS="schedule1-helper-shared-folders-v1",q=s=>document.querySelector(s),esc=v=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c])),types=["recipes","customers","employees","rooms","other"];let activeRealtime=null,activeFolderId=null,roleControlReady=false;
function readSaved(){try{const x=JSON.parse(localStorage.getItem(STORE)||"{}");return Object.fromEntries(types.map(t=>[t,Array.isArray(x[t])?x[t]:[]]));}catch{return Object.fromEntries(types.map(t=>[t,[]]));}}
function localFolders(){try{return JSON.parse(localStorage.getItem(FOLDERS)||"[]");}catch{return[];}}
function encToken(){const b=new Uint8Array(32);crypto.getRandomValues(b);let s="";for(const x of b)s+=String.fromCharCode(x);return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"");}
function dataUrlBlob(src){return fetch(src).then(r=>r.blob());}
function extForBlob(blob){const t=blob.type||"image/jpeg";const m={"image/png":"png","image/jpeg":"jpg","image/webp":"webp","image/gif":"gif","image/avif":"avif"};return m[t]||"bin";}
function snapshotItem(type,item){return{type,key:String(item.key||""),name:String(item.name||"Bez názvu").slice(0,200),note:String(item.note||"").slice(0,5000),image:String(item.image||"")};}
function getItems(){const saved=readSaved(),out=[];for(const type of types)for(const item of saved[type])out.push(snapshotItem(type,item));return out;}
function ensureRoleControl(){const form=q("#sharedFolderForm");if(!form||roleControlReady)return;const submit=form.querySelector("button[type=submit]");if(!submit)return;roleControlReady=true;const label=document.createElement("label");label.className="field-label";label.htmlFor="sharedFolderRole";label.textContent="Oprávnění odkazu";const select=document.createElement("select");select.id="sharedFolderRole";select.innerHTML="<option value='editor'>Editor – může upravovat</option><option value='viewer'>Prohlížeč – pouze čtení</option>";submit.before(label,select);}
function renderPicker(){const root=q("#sharedItemPicker");if(!root)return;const items=getItems();root.innerHTML=items.length?items.map((x,i)=>"<label class='shared-pick'><input type='checkbox' data-i='"+i+"'><span><span class='shared-pick-name'>"+esc(x.name)+"</span><span class='shared-pick-meta'>"+esc(x.note||"")+(x.image?" · obrázek":"")+"</span></span><span class='shared-type'>"+esc(x.type)+"</span></label>").join(""):"<div class='shared-empty'>Nejdřív něco ulož v Moje uložené.</div>";}
async function signedImage(path){if(!path||!window.s1Supabase)return"";const {data}=await window.s1Supabase.storage.from("shared-attachments").createSignedUrl(path,3600);return data?.signedUrl||"";}
async function renderFolderItems(folderId){const root=q("#incomingSharedFolder");const {data:items,error}=await window.s1Supabase.from("shared_items").select("id,item_type,source_key,name,note,image_path,created_at,updated_at").eq("folder_id",folderId).order("created_at",{ascending:true});if(error){root.innerHTML="<div class='empty'>Položky se nepodařilo načíst: "+esc(error.message)+"</div>";return;}const rows=await Promise.all((items||[]).map(async x=>({...x,imageUrl:await signedImage(x.image_path)})));const editor=activeFolderId&&["owner","editor"].includes(window.s1SharedRole);root.innerHTML=rows.map((x,i)=>"<div class='incoming-item' data-shared-item='"+esc(x.id)+"'><label class='field-label'>Název</label><input class='shared-edit-name' data-item='"+esc(x.id)+"' value='"+esc(x.name)+"' maxlength='200' "+(editor?"":"disabled")+"><label class='field-label'>Poznámka</label><textarea class='shared-edit-note' data-item='"+esc(x.id)+"' rows='2' maxlength='5000' "+(editor?"":"disabled")+">"+esc(x.note||"")+"</textarea><div class='shared-type'>"+esc(x.item_type)+(x.image_path?" · obrázek":"")+"</div>"+(x.imageUrl?"<img class='shared-item-image' src='"+esc(x.imageUrl)+"' alt='' style='max-width:180px;max-height:140px;margin-top:7px;border-radius:8px;object-fit:contain'>":"")+(editor?"<input class='shared-edit-image' data-item='"+esc(x.id)+"' type='file' accept='image/*'>":"")+"</div>").join("")||"<div class='empty'>Složka zatím nemá žádné položky.</div>";if(editor){root.querySelectorAll(".shared-edit-name,.shared-edit-note").forEach(el=>el.addEventListener("change",()=>saveSharedItem(el.dataset.item)));root.querySelectorAll(".shared-edit-image").forEach(el=>el.addEventListener("change",()=>uploadSharedItemImage(el.dataset.item,el.files?.[0])));}}
async function loadFolder(folderId){if(!window.s1Supabase)return;activeFolderId=folderId;window.s1SharedRole="viewer";const {data:m}=await window.s1Supabase.from("shared_folder_members").select("role").eq("folder_id",folderId).eq("user_id",window.s1Session?.user?.id||"").maybeSingle();window.s1SharedRole=m?.role||"viewer";const {data:f,error}=await window.s1Supabase.from("shared_folders").select("id,name,note,default_role,created_at,updated_at,share_token").eq("id",folderId).maybeSingle();if(error||!f){q("#incomingSharedFolder").innerHTML="<div class='empty'>Sdílená složka není dostupná.</div>";return;}const url=location.origin+location.pathname+"?folderToken="+encodeURIComponent(f.share_token);q("#incomingSharedFolder").innerHTML="<div class='incoming-title'>"+esc(f.name)+"</div><div class='incoming-note'>"+esc(f.note||"Bez poznámky")+" · role: "+esc(window.s1SharedRole)+"</div><div class='incoming-items' id='sharedServerItems'><div class='meta'>Načítám položky…</div></div><div class='copy-note'>Toto je skutečná serverová složka. Úpravy se ukládají do Supabase a ostatní členové je uvidí podle svých oprávnění.</div><div class='share-actions'><button class='btn' type='button' id='copyServerFolderUrl'>Kopírovat odkaz</button>"+(window.s1SharedRole==="owner"?"<button class='btn ghost' type='button' id='rotateServerFolderToken'>Nový odkaz</button><button class='btn ghost danger' type='button' id='deleteServerFolder'>Smazat složku</button>":"")+"</div><input class='share-url' id='sharedServerFolderUrl' readonly value='"+esc(url)+"'>";q("#sharedFolderMembers")?.remove(); const memberBox=document.createElement("div");memberBox.id="sharedFolderMembers";memberBox.className="shared-members";q("#incomingSharedFolder")?.prepend(memberBox);await renderFolderMembers(folderId);const itemRoot=q("#sharedServerItems");if(itemRoot){const fake=q("#incomingSharedFolder");const original=q("#incomingSharedFolder");await renderFolderItemsFixed(folderId);}q("#copyServerFolderUrl")?.addEventListener("click",async()=>{try{await navigator.clipboard.writeText(url);alert("Odkaz zkopírován.");}catch{}});q("#rotateServerFolderToken")?.addEventListener("click",rotateFolderToken);q("#deleteServerFolder")?.addEventListener("click",deleteFolder);subscribeFolder(folderId);loadSharedNotifications();}
async function renderFolderItemsFixed(folderId){const host=q("#sharedServerItems");if(!host)return;const {data:items,error}=await window.s1Supabase.from("shared_items").select("id,item_type,source_key,name,note,image_path,created_at").eq("folder_id",folderId).order("created_at",{ascending:true});if(error){host.innerHTML="<div class='empty'>"+esc(error.message)+"</div>";return;}const editor=["owner","editor"].includes(window.s1SharedRole);const rows=await Promise.all((items||[]).map(async x=>({...x,imageUrl:await signedImage(x.image_path)})));host.innerHTML=rows.map(x=>"<div class='incoming-item'><label class='field-label'>Název</label><input class='shared-edit-name' data-item='"+esc(x.id)+"' value='"+esc(x.name)+"' maxlength='200' "+(editor?"":"disabled")+"><label class='field-label'>Poznámka</label><textarea class='shared-edit-note' data-item='"+esc(x.id)+"' rows='2' maxlength='5000' "+(editor?"":"disabled")+">"+esc(x.note||"")+"</textarea><div class='shared-type'>"+esc(x.item_type)+(x.image_path?" · obrázek":"")+"</div>"+(x.imageUrl?"<img src='"+esc(x.imageUrl)+"' alt='' style='max-width:180px;max-height:140px;margin-top:7px;border-radius:8px;object-fit:contain'>":"")+(editor?"<input class='shared-edit-image' data-item='"+esc(x.id)+"' type='file' accept='image/*'>":"")+"</div>").join("")||"<div class='empty'>Složka zatím nemá žádné položky.</div>";if(editor){host.querySelectorAll(".shared-edit-name,.shared-edit-note").forEach(el=>el.addEventListener("change",()=>saveSharedItem(el.dataset.item)));host.querySelectorAll(".shared-edit-image").forEach(el=>el.addEventListener("change",()=>uploadSharedItemImage(el.dataset.item,el.files?.[0])));}}
async function refreshOpenFolder(){if(activeFolderId)await renderFolderItemsFixed(activeFolderId);}
async function saveSharedItem(itemId){if(!window.s1Supabase||!["owner","editor"].includes(window.s1SharedRole))return;const name=q(".shared-edit-name[data-item='"+CSS.escape(itemId)+"']")?.value.trim()||"Bez názvu",note=q(".shared-edit-note[data-item='"+CSS.escape(itemId)+"']")?.value.trim()||"";const {error}=await window.s1Supabase.from("shared_items").update({name,note,updated_by:window.s1Session.user.id}).eq("id",itemId);if(error)alert("Uložení se nepodařilo: "+error.message);}
async function uploadSharedItemImage(itemId,file){if(!file||!activeFolderId||!["owner","editor"].includes(window.s1SharedRole))return;const blob=await dataUrlBlob(URL.createObjectURL(file)).catch(()=>file);const ext=extForBlob(blob),path=activeFolderId+"/"+crypto.randomUUID()+"."+ext;const {error}=await window.s1Supabase.storage.from("shared-attachments").upload(path,blob,{contentType:blob.type||file.type||"application/octet-stream",upsert:false});if(error){alert("Obrázek se nepodařilo nahrát: "+error.message);return;}const u=await window.s1Supabase.from("shared_items").update({image_path:path,updated_by:window.s1Session.user.id}).eq("id",itemId);if(u.error)alert("Obrázek byl nahrán, ale odkaz se nepodařilo uložit: "+u.error.message);await refreshOpenFolder();}
function subscribeFolder(folderId){if(activeRealtime)activeRealtime.unsubscribe();activeRealtime=window.s1Supabase.channel("s1-shared-folder-"+folderId).on("postgres_changes",{event:"*",schema:"public",table:"shared_items",filter:"folder_id=eq."+folderId},()=>refreshOpenFolder()).on("postgres_changes",{event:"*",schema:"public",table:"shared_folders",filter:"id=eq."+folderId},()=>loadFolder(folderId)).subscribe();}
async function rotateFolderToken(){if(!activeFolderId)return;const {data,error}=await window.s1Supabase.rpc("rotate_shared_folder_token",{p_folder_id:activeFolderId});if(error){alert("Nový odkaz se nepodařilo vytvořit: "+error.message);return;}await loadFolder(activeFolderId);if(data)alert("Nový odkaz byl vytvořen. Starý odkaz je zneplatněný.");}
async function deleteFolder(){if(!activeFolderId||!confirm("Opravdu smazat celou sdílenou složku?"))return;const {error}=await window.s1Supabase.from("shared_folders").delete().eq("id",activeFolderId);if(error){alert("Smazání se nepodařilo: "+error.message);return;}activeFolderId=null;renderFolders();}
async function claimIncoming(){const token=new URLSearchParams(location.search).get("folderToken");if(!token)return;if(!window.s1Supabase||!window.s1Session){q("#incomingSharedFolder").innerHTML="<div class='incoming-title'>Sdílená složka</div><div class='incoming-note'>Nejdřív se přihlas v sekci Účet. Po přihlášení se odkaz automaticky načte.</div>";return;}const {data,error}=await window.s1Supabase.rpc("claim_shared_folder",{p_share_token:token});if(error){q("#incomingSharedFolder").innerHTML="<div class='empty'>Odkaz není platný nebo byl zrušen: "+esc(error.message)+"</div>";return;}if(data?.[0]?.folder_id){showTabServer();await loadFolder(data[0].folder_id);}}
function showTabServer(){const tab=document.querySelector("[data-tab=shared]");tab?.click();}
async function renderFolders(){
  const root=q("#sharedFolderList");
  if(!root)return;
  if(!window.s1Supabase||!window.s1Session){
    root.innerHTML="<div class='shared-empty'>Pro serverové sdílení se nejdřív přihlas v sekci Účet.</div>";
    return;
  }
  const {data,error}=await window.s1Supabase.from("shared_folders")
    .select("id,name,note,default_role,created_at,updated_at,share_token")
    .order("updated_at",{ascending:false});
  if(error){
    root.innerHTML="<div class='empty'>Složky se nepodařilo načíst: "+esc(error.message)+"</div>";
    return;
  }
  const folders=Array.isArray(data)?data:[];
  root.innerHTML=folders.length
    ? folders.map(f=>`
      <article class="shared-folder">
        <div class="shared-folder-top">
          <div class="shared-folder-name">${esc(f.name)}</div>
          <span class="shared-type">${esc(f.default_role==="editor"?"Editor":"Prohlížeč")}</span>
        </div>
        <div class="shared-folder-note">${esc(f.note||"Bez poznámky")}</div>
        <div class="shared-folder-meta">${esc(new Date(f.updated_at||f.created_at).toLocaleString("cs-CZ"))}</div>
        <div class="shared-folder-actions">
          <button class="btn ghost" type="button" data-open-server-folder="${esc(f.id)}">Otevřít</button>
          <button class="btn" type="button" data-share-server-folder="${esc(f.id)}">Sdílet odkaz</button>
        </div>
      </article>`).join("")
    : "<div class='shared-empty'>Zatím nemáš žádnou serverovou složku.</div>";
  root.querySelectorAll("[data-open-server-folder]").forEach(b=>{
    b.addEventListener("click",()=>loadFolder(b.dataset.openServerFolder).then(refreshOpenFolder));
  });
  root.querySelectorAll("[data-share-server-folder]").forEach(b=>{
    b.addEventListener("click",async()=>{
      const f=folders.find(x=>x.id===b.dataset.shareServerFolder);
      if(!f)return;
      const url=location.origin+location.pathname+"?folderToken="+encodeURIComponent(f.share_token);
      showTabServer();
      q("#incomingSharedFolder").innerHTML=`
        <div class="incoming-title">${esc(f.name)}</div>
        <div class="incoming-note">Odkaz pro ${esc(f.default_role==="editor"?"editaci":"prohlížení")}.</div>
        <input class="share-url" readonly value="${esc(url)}">
        <div class="share-actions"><button class="btn primary" id="copyServerFolderUrl2" type="button">Kopírovat odkaz</button></div>`;
      q("#copyServerFolderUrl2")?.addEventListener("click",async()=>{
        try{await navigator.clipboard.writeText(url);alert("Odkaz zkopírován.");}
        catch{alert("Odkaz je připravený ke zkopírování.");}
      });
    });
  });
}
async function createFolder(e){e.preventDefault();if(!window.s1Supabase||!window.s1Session){alert("Pro vytvoření serverové složky se nejdřív přihlas.");return;}const name=q("#sharedFolderName").value.trim(),note=q("#sharedFolderNote").value.trim(),defaultRole=q("#sharedFolderRole")?.value||"editor";if(!name){alert("Zadej název složky.");return;}const localItems=getItems(),chosen=[...document.querySelectorAll("#sharedItemPicker input[type=checkbox]:checked")].map(x=>localItems[Number(x.dataset.i)]).filter(Boolean).slice(0,200);if(!chosen.length){alert("Vyber alespoň jednu položku.");return;}const {data:f,error}=await window.s1Supabase.from("shared_folders").insert({owner_id:window.s1Session.user.id,name,note,default_role:defaultRole,share_token:encToken()}).select("id,share_token").single();if(error){alert("Složku se nepodařilo vytvořit: "+error.message);return;}for(const item of chosen){const {data:row,error:itemError}=await window.s1Supabase.from("shared_items").insert({folder_id:f.id,item_type:item.type,source_key:item.key,name:item.name,note:item.note,created_by:window.s1Session.user.id,updated_by:window.s1Session.user.id}).select("id").single();if(itemError){alert("Položku "+item.name+" se nepodařilo uložit: "+itemError.message);continue;}if(item.image){try{const blob=await dataUrlBlob(item.image),ext=extForBlob(blob),path=f.id+"/"+crypto.randomUUID()+"."+ext;const up=await window.s1Supabase.storage.from("shared-attachments").upload(path,blob,{contentType:blob.type||"image/jpeg",upsert:false});if(!up.error)await window.s1Supabase.from("shared_items").update({image_path:path,updated_by:window.s1Session.user.id}).eq("id",row.id);}catch(err){console.warn("Upload obrázku selhal",err);}}}q("#sharedFolderForm").reset();renderFolders();renderPicker();await loadFolder(f.id);alert("Serverová sdílená složka byla vytvořena.");}
async function loadSharedNotifications(){
 if(!window.s1Supabase||!window.s1Session)return;
 const {data,error}=await window.s1Supabase.from("shared_notifications").select("id,folder_id,item_id,actor_id,kind,message,read_at,created_at").order("created_at",{ascending:false}).limit(30);
 const root=q("#sharedNotifications"),count=q("#sharedNotificationCount");
 if(error){if(root)root.innerHTML="<div class='meta'>Upozornění se nepodařilo načíst.</div>";return;}
 const unread=(data||[]).filter(x=>!x.read_at).length;
 if(count)count.textContent=String(unread);
 if(root)root.innerHTML=(data||[]).length?(data||[]).map(n=>"<div class='shared-notification "+(n.read_at?"":"unread")+"'><div class='shared-notification-main'><b>"+esc(n.kind==="image"?"🖼️ Obrázek":"📝 Poznámka")+"</b><span>"+esc(n.message)+"</span><small>"+esc(new Date(n.created_at).toLocaleString("cs-CZ"))+"</small></div>"+(n.read_at?"":"<button class='btn ghost' type='button' data-read-notification='"+esc(n.id)+"'>Označit jako přečtené</button>")+"</div>").join(""):"<div class='meta'>Žádná upozornění.</div>";
 root?.querySelectorAll("[data-read-notification]").forEach(b=>b.addEventListener("click",async()=>{await window.s1Supabase.from("shared_notifications").update({read_at:new Date().toISOString()}).eq("id",b.dataset.readNotification);loadSharedNotifications();}));
}
function subscribeNotifications(){
 if(!window.s1Supabase||!window.s1Session)return;
 window.s1NotificationChannel?.unsubscribe();
 window.s1NotificationChannel=window.s1Supabase.channel("s1-notifications-"+window.s1Session.user.id).on("postgres_changes",{event:"INSERT",schema:"public",table:"shared_notifications",filter:"user_id=eq."+window.s1Session.user.id},payload=>{loadSharedNotifications();if(window.Notification&&Notification.permission==="granted")new Notification("Schedule I Helper",{body:payload.new.message});}).subscribe();
}
async function renderFolderMembers(folderId){
 const host=q("#sharedFolderMembers");
 if(!host||!window.s1Supabase)return;
 const {data,error}=await window.s1Supabase.from("shared_folder_members").select("user_id,role,created_at,profiles(display_name,email)").eq("folder_id",folderId).order("created_at",{ascending:true});
 if(error){host.innerHTML="<div class='meta'>Členy se nepodařilo načíst.</div>";return;}
 host.innerHTML=(data||[]).map(m=>"<div class='shared-member'><div><b>"+esc(m.profiles?.display_name||m.profiles?.email||"Uživatel")+"</b><small>"+esc(m.profiles?.email||"")+"</small></div><span class='shared-type'>"+esc(m.role==="owner"?"Vlastník":m.role==="editor"?"Editor":"Prohlížeč")+"</span></div>").join("")||"<div class='meta'>Zatím nikdo další nemá přístup.</div>";
}
function init(){const form=q("#sharedFolderForm");if(!form||form.dataset.ready)return;form.dataset.ready="1";ensureRoleControl();renderPicker();renderFolders();q("#sharedSelectAll")?.addEventListener("click",()=>document.querySelectorAll("#sharedItemPicker input[type=checkbox]").forEach(x=>x.checked=true));q("#sharedClearAll")?.addEventListener("click",()=>document.querySelectorAll("#sharedItemPicker input[type=checkbox]").forEach(x=>x.checked=false));form.addEventListener("submit",createFolder);document.querySelectorAll(".tab").forEach(b=>b.addEventListener("click",()=>{if(b.dataset.tab==="shared"){ensureRoleControl();renderPicker();renderFolders();}}));document.addEventListener("s1-auth-changed",async()=>{ensureRoleControl();renderFolders();await claimIncoming();loadSharedNotifications();subscribeNotifications();});q("#sharedNotificationsBtn")?.addEventListener("click",async()=>{if(window.Notification&&Notification.permission==="default")await Notification.requestPermission();loadSharedNotifications();});claimIncoming();loadSharedNotifications();subscribeNotifications();}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init,{once:true});else init();